/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) func_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_f3 CASADI_PREFIX(f3)
#define casadi_f4 CASADI_PREFIX(f4)
#define casadi_f5 CASADI_PREFIX(f5)
#define casadi_f6 CASADI_PREFIX(f6)
#define casadi_f7 CASADI_PREFIX(f7)
#define casadi_s0 CASADI_PREFIX(s0)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

static const casadi_int casadi_s0[3] = {1, 1, 1};

/* func:(x0)->(x1) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @0 = sin(@0) */
  w0 = sin( w0 );
  /* #2: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  return 0;
}

/* func_acc10:(x0)->(x1[1x10]) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real **res1=res+1, w0, w1;
  const casadi_real **arg1=arg+1;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @0 = sin(@0) */
  w0 = sin( w0 );
  /* #2: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  /* #3: @1 = func(@0) */
  arg1[0]=(&w0);
  res1[0]=(&w1);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #4: output[0][1] = @1 */
  if (res[0]) res[0][1] = w1;
  /* #5: @0 = func(@1) */
  arg1[0]=(&w1);
  res1[0]=(&w0);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #6: output[0][2] = @0 */
  if (res[0]) res[0][2] = w0;
  /* #7: @1 = func(@0) */
  arg1[0]=(&w0);
  res1[0]=(&w1);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #8: output[0][3] = @1 */
  if (res[0]) res[0][3] = w1;
  /* #9: @0 = func(@1) */
  arg1[0]=(&w1);
  res1[0]=(&w0);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #10: output[0][4] = @0 */
  if (res[0]) res[0][4] = w0;
  /* #11: @1 = func(@0) */
  arg1[0]=(&w0);
  res1[0]=(&w1);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #12: output[0][5] = @1 */
  if (res[0]) res[0][5] = w1;
  /* #13: @0 = func(@1) */
  arg1[0]=(&w1);
  res1[0]=(&w0);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #14: output[0][6] = @0 */
  if (res[0]) res[0][6] = w0;
  /* #15: @1 = func(@0) */
  arg1[0]=(&w0);
  res1[0]=(&w1);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #16: output[0][7] = @1 */
  if (res[0]) res[0][7] = w1;
  /* #17: @0 = func(@1) */
  arg1[0]=(&w1);
  res1[0]=(&w0);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #18: output[0][8] = @0 */
  if (res[0]) res[0][8] = w0;
  /* #19: @1 = func(@0) */
  arg1[0]=(&w0);
  res1[0]=(&w1);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #20: output[0][9] = @1 */
  if (res[0]) res[0][9] = w1;
  return 0;
}

/* func_acc10_acc10:(x0)->(x1[1x100]) */
static int casadi_f3(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real **res1=res+1, w0, w1, *w2=w+5;
  const casadi_real **arg1=arg+1;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @0 = sin(@0) */
  w0 = sin( w0 );
  /* #2: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  /* #3: @1 = func(@0) */
  arg1[0]=(&w0);
  res1[0]=(&w1);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #4: output[0][1] = @1 */
  if (res[0]) res[0][1] = w1;
  /* #5: @0 = func(@1) */
  arg1[0]=(&w1);
  res1[0]=(&w0);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #6: output[0][2] = @0 */
  if (res[0]) res[0][2] = w0;
  /* #7: @1 = func(@0) */
  arg1[0]=(&w0);
  res1[0]=(&w1);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #8: output[0][3] = @1 */
  if (res[0]) res[0][3] = w1;
  /* #9: @0 = func(@1) */
  arg1[0]=(&w1);
  res1[0]=(&w0);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #10: output[0][4] = @0 */
  if (res[0]) res[0][4] = w0;
  /* #11: @1 = func(@0) */
  arg1[0]=(&w0);
  res1[0]=(&w1);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #12: output[0][5] = @1 */
  if (res[0]) res[0][5] = w1;
  /* #13: @0 = func(@1) */
  arg1[0]=(&w1);
  res1[0]=(&w0);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #14: output[0][6] = @0 */
  if (res[0]) res[0][6] = w0;
  /* #15: @1 = func(@0) */
  arg1[0]=(&w0);
  res1[0]=(&w1);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #16: output[0][7] = @1 */
  if (res[0]) res[0][7] = w1;
  /* #17: @0 = func(@1) */
  arg1[0]=(&w1);
  res1[0]=(&w0);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #18: output[0][8] = @0 */
  if (res[0]) res[0][8] = w0;
  /* #19: @1 = func(@0) */
  arg1[0]=(&w0);
  res1[0]=(&w1);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #20: output[0][9] = @1 */
  if (res[0]) res[0][9] = w1;
  /* #21: @2 = func_acc10(@1) */
  arg1[0]=(&w1);
  res1[0]=w2;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #22: output[0][10] = @2 */
  if (res[0]) casadi_copy(w2, 10, res[0]+10);
  /* #23: {NULL, @1} = horzsplit(@2) */
  w1 = w2[9];
  /* #24: @2 = func_acc10(@1) */
  arg1[0]=(&w1);
  res1[0]=w2;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #25: output[0][11] = @2 */
  if (res[0]) casadi_copy(w2, 10, res[0]+20);
  /* #26: {NULL, @1} = horzsplit(@2) */
  w1 = w2[9];
  /* #27: @2 = func_acc10(@1) */
  arg1[0]=(&w1);
  res1[0]=w2;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #28: output[0][12] = @2 */
  if (res[0]) casadi_copy(w2, 10, res[0]+30);
  /* #29: {NULL, @1} = horzsplit(@2) */
  w1 = w2[9];
  /* #30: @2 = func_acc10(@1) */
  arg1[0]=(&w1);
  res1[0]=w2;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #31: output[0][13] = @2 */
  if (res[0]) casadi_copy(w2, 10, res[0]+40);
  /* #32: {NULL, @1} = horzsplit(@2) */
  w1 = w2[9];
  /* #33: @2 = func_acc10(@1) */
  arg1[0]=(&w1);
  res1[0]=w2;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #34: output[0][14] = @2 */
  if (res[0]) casadi_copy(w2, 10, res[0]+50);
  /* #35: {NULL, @1} = horzsplit(@2) */
  w1 = w2[9];
  /* #36: @2 = func_acc10(@1) */
  arg1[0]=(&w1);
  res1[0]=w2;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #37: output[0][15] = @2 */
  if (res[0]) casadi_copy(w2, 10, res[0]+60);
  /* #38: {NULL, @1} = horzsplit(@2) */
  w1 = w2[9];
  /* #39: @2 = func_acc10(@1) */
  arg1[0]=(&w1);
  res1[0]=w2;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #40: output[0][16] = @2 */
  if (res[0]) casadi_copy(w2, 10, res[0]+70);
  /* #41: {NULL, @1} = horzsplit(@2) */
  w1 = w2[9];
  /* #42: @2 = func_acc10(@1) */
  arg1[0]=(&w1);
  res1[0]=w2;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #43: output[0][17] = @2 */
  if (res[0]) casadi_copy(w2, 10, res[0]+80);
  /* #44: {NULL, @1} = horzsplit(@2) */
  w1 = w2[9];
  /* #45: @2 = func_acc10(@1) */
  arg1[0]=(&w1);
  res1[0]=w2;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #46: output[0][18] = @2 */
  if (res[0]) casadi_copy(w2, 10, res[0]+90);
  return 0;
}

/* func_acc10_acc10_acc10:(x0)->(x1[1x1000]) */
static int casadi_f4(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real **res1=res+1, *rr, w00, w01, w02, w03, w04, w05, w06, w07, w08, w09;
  casadi_real *w10=w+25, w11, *w12=w+36, *w13=w+46, *w14=w+56, *w15=w+66, *w16=w+76, *w17=w+86, *w18=w+96, *w19=w+106, *w20=w+116;
  const casadi_real **arg1=arg+1, *cs;
  /* #0: @0 = input[0][0] */
  w00 = arg[0] ? arg[0][0] : 0;
  /* #1: @0 = sin(@0) */
  w00 = sin( w00 );
  /* #2: output[0][0] = @0 */
  if (res[0]) res[0][0] = w00;
  /* #3: @1 = func(@0) */
  arg1[0]=(&w00);
  res1[0]=(&w01);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #4: output[0][1] = @1 */
  if (res[0]) res[0][1] = w01;
  /* #5: @2 = func(@1) */
  arg1[0]=(&w01);
  res1[0]=(&w02);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #6: output[0][2] = @2 */
  if (res[0]) res[0][2] = w02;
  /* #7: @3 = func(@2) */
  arg1[0]=(&w02);
  res1[0]=(&w03);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #8: output[0][3] = @3 */
  if (res[0]) res[0][3] = w03;
  /* #9: @4 = func(@3) */
  arg1[0]=(&w03);
  res1[0]=(&w04);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #10: output[0][4] = @4 */
  if (res[0]) res[0][4] = w04;
  /* #11: @5 = func(@4) */
  arg1[0]=(&w04);
  res1[0]=(&w05);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #12: output[0][5] = @5 */
  if (res[0]) res[0][5] = w05;
  /* #13: @6 = func(@5) */
  arg1[0]=(&w05);
  res1[0]=(&w06);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #14: output[0][6] = @6 */
  if (res[0]) res[0][6] = w06;
  /* #15: @7 = func(@6) */
  arg1[0]=(&w06);
  res1[0]=(&w07);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #16: output[0][7] = @7 */
  if (res[0]) res[0][7] = w07;
  /* #17: @8 = func(@7) */
  arg1[0]=(&w07);
  res1[0]=(&w08);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #18: output[0][8] = @8 */
  if (res[0]) res[0][8] = w08;
  /* #19: @9 = func(@8) */
  arg1[0]=(&w08);
  res1[0]=(&w09);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #20: output[0][9] = @9 */
  if (res[0]) res[0][9] = w09;
  /* #21: @10 = func_acc10(@9) */
  arg1[0]=(&w09);
  res1[0]=w10;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #22: output[0][10] = @10 */
  if (res[0]) casadi_copy(w10, 10, res[0]+10);
  /* #23: {NULL, @11} = horzsplit(@10) */
  w11 = w10[9];
  /* #24: @12 = func_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w12;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #25: output[0][11] = @12 */
  if (res[0]) casadi_copy(w12, 10, res[0]+20);
  /* #26: {NULL, @11} = horzsplit(@12) */
  w11 = w12[9];
  /* #27: @13 = func_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w13;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #28: output[0][12] = @13 */
  if (res[0]) casadi_copy(w13, 10, res[0]+30);
  /* #29: {NULL, @11} = horzsplit(@13) */
  w11 = w13[9];
  /* #30: @14 = func_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w14;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #31: output[0][13] = @14 */
  if (res[0]) casadi_copy(w14, 10, res[0]+40);
  /* #32: {NULL, @11} = horzsplit(@14) */
  w11 = w14[9];
  /* #33: @15 = func_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w15;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #34: output[0][14] = @15 */
  if (res[0]) casadi_copy(w15, 10, res[0]+50);
  /* #35: {NULL, @11} = horzsplit(@15) */
  w11 = w15[9];
  /* #36: @16 = func_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w16;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #37: output[0][15] = @16 */
  if (res[0]) casadi_copy(w16, 10, res[0]+60);
  /* #38: {NULL, @11} = horzsplit(@16) */
  w11 = w16[9];
  /* #39: @17 = func_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w17;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #40: output[0][16] = @17 */
  if (res[0]) casadi_copy(w17, 10, res[0]+70);
  /* #41: {NULL, @11} = horzsplit(@17) */
  w11 = w17[9];
  /* #42: @18 = func_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w18;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #43: output[0][17] = @18 */
  if (res[0]) casadi_copy(w18, 10, res[0]+80);
  /* #44: {NULL, @11} = horzsplit(@18) */
  w11 = w18[9];
  /* #45: @19 = func_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w19;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #46: output[0][18] = @19 */
  if (res[0]) casadi_copy(w19, 10, res[0]+90);
  /* #47: @20 = horzcat(@0, @1, @2, @3, @4, @5, @6, @7, @8, @9, @10, @12, @13, @14, @15, @16, @17, @18, @19) */
  rr=w20;
  *rr++ = w00;
  *rr++ = w01;
  *rr++ = w02;
  *rr++ = w03;
  *rr++ = w04;
  *rr++ = w05;
  *rr++ = w06;
  *rr++ = w07;
  *rr++ = w08;
  *rr++ = w09;
  for (i=0, cs=w10; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w12; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w13; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w14; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w15; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w16; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w17; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w18; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w19; i<10; ++i) *rr++ = *cs++;
  /* #48: {NULL, @0} = horzsplit(@20) */
  w00 = w20[99];
  /* #49: @20 = func_acc10_acc10(@0) */
  arg1[0]=(&w00);
  res1[0]=w20;
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #50: output[0][19] = @20 */
  if (res[0]) casadi_copy(w20, 100, res[0]+100);
  /* #51: {NULL, @0} = horzsplit(@20) */
  w00 = w20[99];
  /* #52: @20 = func_acc10_acc10(@0) */
  arg1[0]=(&w00);
  res1[0]=w20;
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #53: output[0][20] = @20 */
  if (res[0]) casadi_copy(w20, 100, res[0]+200);
  /* #54: {NULL, @0} = horzsplit(@20) */
  w00 = w20[99];
  /* #55: @20 = func_acc10_acc10(@0) */
  arg1[0]=(&w00);
  res1[0]=w20;
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #56: output[0][21] = @20 */
  if (res[0]) casadi_copy(w20, 100, res[0]+300);
  /* #57: {NULL, @0} = horzsplit(@20) */
  w00 = w20[99];
  /* #58: @20 = func_acc10_acc10(@0) */
  arg1[0]=(&w00);
  res1[0]=w20;
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #59: output[0][22] = @20 */
  if (res[0]) casadi_copy(w20, 100, res[0]+400);
  /* #60: {NULL, @0} = horzsplit(@20) */
  w00 = w20[99];
  /* #61: @20 = func_acc10_acc10(@0) */
  arg1[0]=(&w00);
  res1[0]=w20;
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #62: output[0][23] = @20 */
  if (res[0]) casadi_copy(w20, 100, res[0]+500);
  /* #63: {NULL, @0} = horzsplit(@20) */
  w00 = w20[99];
  /* #64: @20 = func_acc10_acc10(@0) */
  arg1[0]=(&w00);
  res1[0]=w20;
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #65: output[0][24] = @20 */
  if (res[0]) casadi_copy(w20, 100, res[0]+600);
  /* #66: {NULL, @0} = horzsplit(@20) */
  w00 = w20[99];
  /* #67: @20 = func_acc10_acc10(@0) */
  arg1[0]=(&w00);
  res1[0]=w20;
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #68: output[0][25] = @20 */
  if (res[0]) casadi_copy(w20, 100, res[0]+700);
  /* #69: {NULL, @0} = horzsplit(@20) */
  w00 = w20[99];
  /* #70: @20 = func_acc10_acc10(@0) */
  arg1[0]=(&w00);
  res1[0]=w20;
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #71: output[0][26] = @20 */
  if (res[0]) casadi_copy(w20, 100, res[0]+800);
  /* #72: {NULL, @0} = horzsplit(@20) */
  w00 = w20[99];
  /* #73: @20 = func_acc10_acc10(@0) */
  arg1[0]=(&w00);
  res1[0]=w20;
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #74: output[0][27] = @20 */
  if (res[0]) casadi_copy(w20, 100, res[0]+900);
  return 0;
}

/* func_acc10_acc10_acc10_acc10:(x0)->(x1[1x10000]) */
static int casadi_f5(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real **res1=res+1, *rr, w00, w01, w02, w03, w04, w05, w06, w07, w08, w09;
  casadi_real *w10=w+226, w11, *w12=w+237, *w13=w+247, *w14=w+257, *w15=w+267, *w16=w+277, *w17=w+287, *w18=w+297, *w19=w+307, *w20=w+317, *w21=w+417;
  casadi_real *w22=w+517, *w23=w+617, *w24=w+717, *w25=w+817, *w26=w+917, *w27=w+1017, *w28=w+1117, *w29=w+1217;
  const casadi_real **arg1=arg+1, *cs;
  /* #0: @0 = input[0][0] */
  w00 = arg[0] ? arg[0][0] : 0;
  /* #1: @0 = sin(@0) */
  w00 = sin( w00 );
  /* #2: output[0][0] = @0 */
  if (res[0]) res[0][0] = w00;
  /* #3: @1 = func(@0) */
  arg1[0]=(&w00);
  res1[0]=(&w01);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #4: output[0][1] = @1 */
  if (res[0]) res[0][1] = w01;
  /* #5: @2 = func(@1) */
  arg1[0]=(&w01);
  res1[0]=(&w02);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #6: output[0][2] = @2 */
  if (res[0]) res[0][2] = w02;
  /* #7: @3 = func(@2) */
  arg1[0]=(&w02);
  res1[0]=(&w03);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #8: output[0][3] = @3 */
  if (res[0]) res[0][3] = w03;
  /* #9: @4 = func(@3) */
  arg1[0]=(&w03);
  res1[0]=(&w04);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #10: output[0][4] = @4 */
  if (res[0]) res[0][4] = w04;
  /* #11: @5 = func(@4) */
  arg1[0]=(&w04);
  res1[0]=(&w05);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #12: output[0][5] = @5 */
  if (res[0]) res[0][5] = w05;
  /* #13: @6 = func(@5) */
  arg1[0]=(&w05);
  res1[0]=(&w06);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #14: output[0][6] = @6 */
  if (res[0]) res[0][6] = w06;
  /* #15: @7 = func(@6) */
  arg1[0]=(&w06);
  res1[0]=(&w07);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #16: output[0][7] = @7 */
  if (res[0]) res[0][7] = w07;
  /* #17: @8 = func(@7) */
  arg1[0]=(&w07);
  res1[0]=(&w08);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #18: output[0][8] = @8 */
  if (res[0]) res[0][8] = w08;
  /* #19: @9 = func(@8) */
  arg1[0]=(&w08);
  res1[0]=(&w09);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #20: output[0][9] = @9 */
  if (res[0]) res[0][9] = w09;
  /* #21: @10 = func_acc10(@9) */
  arg1[0]=(&w09);
  res1[0]=w10;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #22: output[0][10] = @10 */
  if (res[0]) casadi_copy(w10, 10, res[0]+10);
  /* #23: {NULL, @11} = horzsplit(@10) */
  w11 = w10[9];
  /* #24: @12 = func_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w12;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #25: output[0][11] = @12 */
  if (res[0]) casadi_copy(w12, 10, res[0]+20);
  /* #26: {NULL, @11} = horzsplit(@12) */
  w11 = w12[9];
  /* #27: @13 = func_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w13;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #28: output[0][12] = @13 */
  if (res[0]) casadi_copy(w13, 10, res[0]+30);
  /* #29: {NULL, @11} = horzsplit(@13) */
  w11 = w13[9];
  /* #30: @14 = func_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w14;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #31: output[0][13] = @14 */
  if (res[0]) casadi_copy(w14, 10, res[0]+40);
  /* #32: {NULL, @11} = horzsplit(@14) */
  w11 = w14[9];
  /* #33: @15 = func_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w15;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #34: output[0][14] = @15 */
  if (res[0]) casadi_copy(w15, 10, res[0]+50);
  /* #35: {NULL, @11} = horzsplit(@15) */
  w11 = w15[9];
  /* #36: @16 = func_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w16;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #37: output[0][15] = @16 */
  if (res[0]) casadi_copy(w16, 10, res[0]+60);
  /* #38: {NULL, @11} = horzsplit(@16) */
  w11 = w16[9];
  /* #39: @17 = func_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w17;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #40: output[0][16] = @17 */
  if (res[0]) casadi_copy(w17, 10, res[0]+70);
  /* #41: {NULL, @11} = horzsplit(@17) */
  w11 = w17[9];
  /* #42: @18 = func_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w18;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #43: output[0][17] = @18 */
  if (res[0]) casadi_copy(w18, 10, res[0]+80);
  /* #44: {NULL, @11} = horzsplit(@18) */
  w11 = w18[9];
  /* #45: @19 = func_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w19;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #46: output[0][18] = @19 */
  if (res[0]) casadi_copy(w19, 10, res[0]+90);
  /* #47: @20 = horzcat(@0, @1, @2, @3, @4, @5, @6, @7, @8, @9, @10, @12, @13, @14, @15, @16, @17, @18, @19) */
  rr=w20;
  *rr++ = w00;
  *rr++ = w01;
  *rr++ = w02;
  *rr++ = w03;
  *rr++ = w04;
  *rr++ = w05;
  *rr++ = w06;
  *rr++ = w07;
  *rr++ = w08;
  *rr++ = w09;
  for (i=0, cs=w10; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w12; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w13; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w14; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w15; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w16; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w17; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w18; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w19; i<10; ++i) *rr++ = *cs++;
  /* #48: {NULL, @11} = horzsplit(@20) */
  w11 = w20[99];
  /* #49: @20 = func_acc10_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w20;
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #50: output[0][19] = @20 */
  if (res[0]) casadi_copy(w20, 100, res[0]+100);
  /* #51: {NULL, @11} = horzsplit(@20) */
  w11 = w20[99];
  /* #52: @21 = func_acc10_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w21;
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #53: output[0][20] = @21 */
  if (res[0]) casadi_copy(w21, 100, res[0]+200);
  /* #54: {NULL, @11} = horzsplit(@21) */
  w11 = w21[99];
  /* #55: @22 = func_acc10_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w22;
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #56: output[0][21] = @22 */
  if (res[0]) casadi_copy(w22, 100, res[0]+300);
  /* #57: {NULL, @11} = horzsplit(@22) */
  w11 = w22[99];
  /* #58: @23 = func_acc10_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w23;
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #59: output[0][22] = @23 */
  if (res[0]) casadi_copy(w23, 100, res[0]+400);
  /* #60: {NULL, @11} = horzsplit(@23) */
  w11 = w23[99];
  /* #61: @24 = func_acc10_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w24;
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #62: output[0][23] = @24 */
  if (res[0]) casadi_copy(w24, 100, res[0]+500);
  /* #63: {NULL, @11} = horzsplit(@24) */
  w11 = w24[99];
  /* #64: @25 = func_acc10_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w25;
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #65: output[0][24] = @25 */
  if (res[0]) casadi_copy(w25, 100, res[0]+600);
  /* #66: {NULL, @11} = horzsplit(@25) */
  w11 = w25[99];
  /* #67: @26 = func_acc10_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w26;
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #68: output[0][25] = @26 */
  if (res[0]) casadi_copy(w26, 100, res[0]+700);
  /* #69: {NULL, @11} = horzsplit(@26) */
  w11 = w26[99];
  /* #70: @27 = func_acc10_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w27;
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #71: output[0][26] = @27 */
  if (res[0]) casadi_copy(w27, 100, res[0]+800);
  /* #72: {NULL, @11} = horzsplit(@27) */
  w11 = w27[99];
  /* #73: @28 = func_acc10_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w28;
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #74: output[0][27] = @28 */
  if (res[0]) casadi_copy(w28, 100, res[0]+900);
  /* #75: @29 = horzcat(@0, @1, @2, @3, @4, @5, @6, @7, @8, @9, @10, @12, @13, @14, @15, @16, @17, @18, @19, @20, @21, @22, @23, @24, @25, @26, @27, @28) */
  rr=w29;
  *rr++ = w00;
  *rr++ = w01;
  *rr++ = w02;
  *rr++ = w03;
  *rr++ = w04;
  *rr++ = w05;
  *rr++ = w06;
  *rr++ = w07;
  *rr++ = w08;
  *rr++ = w09;
  for (i=0, cs=w10; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w12; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w13; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w14; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w15; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w16; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w17; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w18; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w19; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w20; i<100; ++i) *rr++ = *cs++;
  for (i=0, cs=w21; i<100; ++i) *rr++ = *cs++;
  for (i=0, cs=w22; i<100; ++i) *rr++ = *cs++;
  for (i=0, cs=w23; i<100; ++i) *rr++ = *cs++;
  for (i=0, cs=w24; i<100; ++i) *rr++ = *cs++;
  for (i=0, cs=w25; i<100; ++i) *rr++ = *cs++;
  for (i=0, cs=w26; i<100; ++i) *rr++ = *cs++;
  for (i=0, cs=w27; i<100; ++i) *rr++ = *cs++;
  for (i=0, cs=w28; i<100; ++i) *rr++ = *cs++;
  /* #76: {NULL, @0} = horzsplit(@29) */
  w00 = w29[999];
  /* #77: @29 = func_acc10_acc10_acc10(@0) */
  arg1[0]=(&w00);
  res1[0]=w29;
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #78: output[0][28] = @29 */
  if (res[0]) casadi_copy(w29, 1000, res[0]+1000);
  /* #79: {NULL, @0} = horzsplit(@29) */
  w00 = w29[999];
  /* #80: @29 = func_acc10_acc10_acc10(@0) */
  arg1[0]=(&w00);
  res1[0]=w29;
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #81: output[0][29] = @29 */
  if (res[0]) casadi_copy(w29, 1000, res[0]+2000);
  /* #82: {NULL, @0} = horzsplit(@29) */
  w00 = w29[999];
  /* #83: @29 = func_acc10_acc10_acc10(@0) */
  arg1[0]=(&w00);
  res1[0]=w29;
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #84: output[0][30] = @29 */
  if (res[0]) casadi_copy(w29, 1000, res[0]+3000);
  /* #85: {NULL, @0} = horzsplit(@29) */
  w00 = w29[999];
  /* #86: @29 = func_acc10_acc10_acc10(@0) */
  arg1[0]=(&w00);
  res1[0]=w29;
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #87: output[0][31] = @29 */
  if (res[0]) casadi_copy(w29, 1000, res[0]+4000);
  /* #88: {NULL, @0} = horzsplit(@29) */
  w00 = w29[999];
  /* #89: @29 = func_acc10_acc10_acc10(@0) */
  arg1[0]=(&w00);
  res1[0]=w29;
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #90: output[0][32] = @29 */
  if (res[0]) casadi_copy(w29, 1000, res[0]+5000);
  /* #91: {NULL, @0} = horzsplit(@29) */
  w00 = w29[999];
  /* #92: @29 = func_acc10_acc10_acc10(@0) */
  arg1[0]=(&w00);
  res1[0]=w29;
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #93: output[0][33] = @29 */
  if (res[0]) casadi_copy(w29, 1000, res[0]+6000);
  /* #94: {NULL, @0} = horzsplit(@29) */
  w00 = w29[999];
  /* #95: @29 = func_acc10_acc10_acc10(@0) */
  arg1[0]=(&w00);
  res1[0]=w29;
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #96: output[0][34] = @29 */
  if (res[0]) casadi_copy(w29, 1000, res[0]+7000);
  /* #97: {NULL, @0} = horzsplit(@29) */
  w00 = w29[999];
  /* #98: @29 = func_acc10_acc10_acc10(@0) */
  arg1[0]=(&w00);
  res1[0]=w29;
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #99: output[0][35] = @29 */
  if (res[0]) casadi_copy(w29, 1000, res[0]+8000);
  /* #100: {NULL, @0} = horzsplit(@29) */
  w00 = w29[999];
  /* #101: @29 = func_acc10_acc10_acc10(@0) */
  arg1[0]=(&w00);
  res1[0]=w29;
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #102: output[0][36] = @29 */
  if (res[0]) casadi_copy(w29, 1000, res[0]+9000);
  return 0;
}

/* func_acc10_acc10_acc10_acc10_acc10:(x0)->(x1[1x100000]) */
static int casadi_f6(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real **res1=res+1, *rr, w00, w01, w02, w03, w04, w05, w06, w07, w08, w09;
  casadi_real *w10=w+2227, w11, *w12=w+2238, *w13=w+2248, *w14=w+2258, *w15=w+2268, *w16=w+2278, *w17=w+2288, *w18=w+2298, *w19=w+2308, *w20=w+2318, *w21=w+2418;
  casadi_real *w22=w+2518, *w23=w+2618, *w24=w+2718, *w25=w+2818, *w26=w+2918, *w27=w+3018, *w28=w+3118, *w29=w+3218, *w30=w+4218, *w31=w+5218, *w32=w+6218, *w33=w+7218;
  casadi_real *w34=w+8218, *w35=w+9218, *w36=w+10218, *w37=w+11218, *w38=w+12218;
  const casadi_real **arg1=arg+1, *cs;
  /* #0: @0 = input[0][0] */
  w00 = arg[0] ? arg[0][0] : 0;
  /* #1: @0 = sin(@0) */
  w00 = sin( w00 );
  /* #2: output[0][0] = @0 */
  if (res[0]) res[0][0] = w00;
  /* #3: @1 = func(@0) */
  arg1[0]=(&w00);
  res1[0]=(&w01);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #4: output[0][1] = @1 */
  if (res[0]) res[0][1] = w01;
  /* #5: @2 = func(@1) */
  arg1[0]=(&w01);
  res1[0]=(&w02);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #6: output[0][2] = @2 */
  if (res[0]) res[0][2] = w02;
  /* #7: @3 = func(@2) */
  arg1[0]=(&w02);
  res1[0]=(&w03);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #8: output[0][3] = @3 */
  if (res[0]) res[0][3] = w03;
  /* #9: @4 = func(@3) */
  arg1[0]=(&w03);
  res1[0]=(&w04);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #10: output[0][4] = @4 */
  if (res[0]) res[0][4] = w04;
  /* #11: @5 = func(@4) */
  arg1[0]=(&w04);
  res1[0]=(&w05);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #12: output[0][5] = @5 */
  if (res[0]) res[0][5] = w05;
  /* #13: @6 = func(@5) */
  arg1[0]=(&w05);
  res1[0]=(&w06);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #14: output[0][6] = @6 */
  if (res[0]) res[0][6] = w06;
  /* #15: @7 = func(@6) */
  arg1[0]=(&w06);
  res1[0]=(&w07);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #16: output[0][7] = @7 */
  if (res[0]) res[0][7] = w07;
  /* #17: @8 = func(@7) */
  arg1[0]=(&w07);
  res1[0]=(&w08);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #18: output[0][8] = @8 */
  if (res[0]) res[0][8] = w08;
  /* #19: @9 = func(@8) */
  arg1[0]=(&w08);
  res1[0]=(&w09);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #20: output[0][9] = @9 */
  if (res[0]) res[0][9] = w09;
  /* #21: @10 = func_acc10(@9) */
  arg1[0]=(&w09);
  res1[0]=w10;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #22: output[0][10] = @10 */
  if (res[0]) casadi_copy(w10, 10, res[0]+10);
  /* #23: {NULL, @11} = horzsplit(@10) */
  w11 = w10[9];
  /* #24: @12 = func_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w12;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #25: output[0][11] = @12 */
  if (res[0]) casadi_copy(w12, 10, res[0]+20);
  /* #26: {NULL, @11} = horzsplit(@12) */
  w11 = w12[9];
  /* #27: @13 = func_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w13;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #28: output[0][12] = @13 */
  if (res[0]) casadi_copy(w13, 10, res[0]+30);
  /* #29: {NULL, @11} = horzsplit(@13) */
  w11 = w13[9];
  /* #30: @14 = func_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w14;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #31: output[0][13] = @14 */
  if (res[0]) casadi_copy(w14, 10, res[0]+40);
  /* #32: {NULL, @11} = horzsplit(@14) */
  w11 = w14[9];
  /* #33: @15 = func_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w15;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #34: output[0][14] = @15 */
  if (res[0]) casadi_copy(w15, 10, res[0]+50);
  /* #35: {NULL, @11} = horzsplit(@15) */
  w11 = w15[9];
  /* #36: @16 = func_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w16;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #37: output[0][15] = @16 */
  if (res[0]) casadi_copy(w16, 10, res[0]+60);
  /* #38: {NULL, @11} = horzsplit(@16) */
  w11 = w16[9];
  /* #39: @17 = func_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w17;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #40: output[0][16] = @17 */
  if (res[0]) casadi_copy(w17, 10, res[0]+70);
  /* #41: {NULL, @11} = horzsplit(@17) */
  w11 = w17[9];
  /* #42: @18 = func_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w18;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #43: output[0][17] = @18 */
  if (res[0]) casadi_copy(w18, 10, res[0]+80);
  /* #44: {NULL, @11} = horzsplit(@18) */
  w11 = w18[9];
  /* #45: @19 = func_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w19;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #46: output[0][18] = @19 */
  if (res[0]) casadi_copy(w19, 10, res[0]+90);
  /* #47: @20 = horzcat(@0, @1, @2, @3, @4, @5, @6, @7, @8, @9, @10, @12, @13, @14, @15, @16, @17, @18, @19) */
  rr=w20;
  *rr++ = w00;
  *rr++ = w01;
  *rr++ = w02;
  *rr++ = w03;
  *rr++ = w04;
  *rr++ = w05;
  *rr++ = w06;
  *rr++ = w07;
  *rr++ = w08;
  *rr++ = w09;
  for (i=0, cs=w10; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w12; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w13; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w14; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w15; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w16; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w17; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w18; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w19; i<10; ++i) *rr++ = *cs++;
  /* #48: {NULL, @11} = horzsplit(@20) */
  w11 = w20[99];
  /* #49: @20 = func_acc10_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w20;
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #50: output[0][19] = @20 */
  if (res[0]) casadi_copy(w20, 100, res[0]+100);
  /* #51: {NULL, @11} = horzsplit(@20) */
  w11 = w20[99];
  /* #52: @21 = func_acc10_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w21;
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #53: output[0][20] = @21 */
  if (res[0]) casadi_copy(w21, 100, res[0]+200);
  /* #54: {NULL, @11} = horzsplit(@21) */
  w11 = w21[99];
  /* #55: @22 = func_acc10_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w22;
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #56: output[0][21] = @22 */
  if (res[0]) casadi_copy(w22, 100, res[0]+300);
  /* #57: {NULL, @11} = horzsplit(@22) */
  w11 = w22[99];
  /* #58: @23 = func_acc10_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w23;
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #59: output[0][22] = @23 */
  if (res[0]) casadi_copy(w23, 100, res[0]+400);
  /* #60: {NULL, @11} = horzsplit(@23) */
  w11 = w23[99];
  /* #61: @24 = func_acc10_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w24;
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #62: output[0][23] = @24 */
  if (res[0]) casadi_copy(w24, 100, res[0]+500);
  /* #63: {NULL, @11} = horzsplit(@24) */
  w11 = w24[99];
  /* #64: @25 = func_acc10_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w25;
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #65: output[0][24] = @25 */
  if (res[0]) casadi_copy(w25, 100, res[0]+600);
  /* #66: {NULL, @11} = horzsplit(@25) */
  w11 = w25[99];
  /* #67: @26 = func_acc10_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w26;
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #68: output[0][25] = @26 */
  if (res[0]) casadi_copy(w26, 100, res[0]+700);
  /* #69: {NULL, @11} = horzsplit(@26) */
  w11 = w26[99];
  /* #70: @27 = func_acc10_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w27;
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #71: output[0][26] = @27 */
  if (res[0]) casadi_copy(w27, 100, res[0]+800);
  /* #72: {NULL, @11} = horzsplit(@27) */
  w11 = w27[99];
  /* #73: @28 = func_acc10_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w28;
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #74: output[0][27] = @28 */
  if (res[0]) casadi_copy(w28, 100, res[0]+900);
  /* #75: @29 = horzcat(@0, @1, @2, @3, @4, @5, @6, @7, @8, @9, @10, @12, @13, @14, @15, @16, @17, @18, @19, @20, @21, @22, @23, @24, @25, @26, @27, @28) */
  rr=w29;
  *rr++ = w00;
  *rr++ = w01;
  *rr++ = w02;
  *rr++ = w03;
  *rr++ = w04;
  *rr++ = w05;
  *rr++ = w06;
  *rr++ = w07;
  *rr++ = w08;
  *rr++ = w09;
  for (i=0, cs=w10; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w12; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w13; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w14; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w15; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w16; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w17; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w18; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w19; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w20; i<100; ++i) *rr++ = *cs++;
  for (i=0, cs=w21; i<100; ++i) *rr++ = *cs++;
  for (i=0, cs=w22; i<100; ++i) *rr++ = *cs++;
  for (i=0, cs=w23; i<100; ++i) *rr++ = *cs++;
  for (i=0, cs=w24; i<100; ++i) *rr++ = *cs++;
  for (i=0, cs=w25; i<100; ++i) *rr++ = *cs++;
  for (i=0, cs=w26; i<100; ++i) *rr++ = *cs++;
  for (i=0, cs=w27; i<100; ++i) *rr++ = *cs++;
  for (i=0, cs=w28; i<100; ++i) *rr++ = *cs++;
  /* #76: {NULL, @11} = horzsplit(@29) */
  w11 = w29[999];
  /* #77: @29 = func_acc10_acc10_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w29;
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #78: output[0][28] = @29 */
  if (res[0]) casadi_copy(w29, 1000, res[0]+1000);
  /* #79: {NULL, @11} = horzsplit(@29) */
  w11 = w29[999];
  /* #80: @30 = func_acc10_acc10_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w30;
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #81: output[0][29] = @30 */
  if (res[0]) casadi_copy(w30, 1000, res[0]+2000);
  /* #82: {NULL, @11} = horzsplit(@30) */
  w11 = w30[999];
  /* #83: @31 = func_acc10_acc10_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w31;
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #84: output[0][30] = @31 */
  if (res[0]) casadi_copy(w31, 1000, res[0]+3000);
  /* #85: {NULL, @11} = horzsplit(@31) */
  w11 = w31[999];
  /* #86: @32 = func_acc10_acc10_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w32;
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #87: output[0][31] = @32 */
  if (res[0]) casadi_copy(w32, 1000, res[0]+4000);
  /* #88: {NULL, @11} = horzsplit(@32) */
  w11 = w32[999];
  /* #89: @33 = func_acc10_acc10_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w33;
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #90: output[0][32] = @33 */
  if (res[0]) casadi_copy(w33, 1000, res[0]+5000);
  /* #91: {NULL, @11} = horzsplit(@33) */
  w11 = w33[999];
  /* #92: @34 = func_acc10_acc10_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w34;
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #93: output[0][33] = @34 */
  if (res[0]) casadi_copy(w34, 1000, res[0]+6000);
  /* #94: {NULL, @11} = horzsplit(@34) */
  w11 = w34[999];
  /* #95: @35 = func_acc10_acc10_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w35;
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #96: output[0][34] = @35 */
  if (res[0]) casadi_copy(w35, 1000, res[0]+7000);
  /* #97: {NULL, @11} = horzsplit(@35) */
  w11 = w35[999];
  /* #98: @36 = func_acc10_acc10_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w36;
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #99: output[0][35] = @36 */
  if (res[0]) casadi_copy(w36, 1000, res[0]+8000);
  /* #100: {NULL, @11} = horzsplit(@36) */
  w11 = w36[999];
  /* #101: @37 = func_acc10_acc10_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w37;
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #102: output[0][36] = @37 */
  if (res[0]) casadi_copy(w37, 1000, res[0]+9000);
  /* #103: @38 = horzcat(@0, @1, @2, @3, @4, @5, @6, @7, @8, @9, @10, @12, @13, @14, @15, @16, @17, @18, @19, @20, @21, @22, @23, @24, @25, @26, @27, @28, @29, @30, @31, @32, @33, @34, @35, @36, @37) */
  rr=w38;
  *rr++ = w00;
  *rr++ = w01;
  *rr++ = w02;
  *rr++ = w03;
  *rr++ = w04;
  *rr++ = w05;
  *rr++ = w06;
  *rr++ = w07;
  *rr++ = w08;
  *rr++ = w09;
  for (i=0, cs=w10; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w12; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w13; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w14; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w15; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w16; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w17; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w18; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w19; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w20; i<100; ++i) *rr++ = *cs++;
  for (i=0, cs=w21; i<100; ++i) *rr++ = *cs++;
  for (i=0, cs=w22; i<100; ++i) *rr++ = *cs++;
  for (i=0, cs=w23; i<100; ++i) *rr++ = *cs++;
  for (i=0, cs=w24; i<100; ++i) *rr++ = *cs++;
  for (i=0, cs=w25; i<100; ++i) *rr++ = *cs++;
  for (i=0, cs=w26; i<100; ++i) *rr++ = *cs++;
  for (i=0, cs=w27; i<100; ++i) *rr++ = *cs++;
  for (i=0, cs=w28; i<100; ++i) *rr++ = *cs++;
  for (i=0, cs=w29; i<1000; ++i) *rr++ = *cs++;
  for (i=0, cs=w30; i<1000; ++i) *rr++ = *cs++;
  for (i=0, cs=w31; i<1000; ++i) *rr++ = *cs++;
  for (i=0, cs=w32; i<1000; ++i) *rr++ = *cs++;
  for (i=0, cs=w33; i<1000; ++i) *rr++ = *cs++;
  for (i=0, cs=w34; i<1000; ++i) *rr++ = *cs++;
  for (i=0, cs=w35; i<1000; ++i) *rr++ = *cs++;
  for (i=0, cs=w36; i<1000; ++i) *rr++ = *cs++;
  for (i=0, cs=w37; i<1000; ++i) *rr++ = *cs++;
  /* #104: {NULL, @0} = horzsplit(@38) */
  w00 = w38[9999];
  /* #105: @38 = func_acc10_acc10_acc10_acc10(@0) */
  arg1[0]=(&w00);
  res1[0]=w38;
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #106: output[0][37] = @38 */
  if (res[0]) casadi_copy(w38, 10000, res[0]+10000);
  /* #107: {NULL, @0} = horzsplit(@38) */
  w00 = w38[9999];
  /* #108: @38 = func_acc10_acc10_acc10_acc10(@0) */
  arg1[0]=(&w00);
  res1[0]=w38;
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #109: output[0][38] = @38 */
  if (res[0]) casadi_copy(w38, 10000, res[0]+20000);
  /* #110: {NULL, @0} = horzsplit(@38) */
  w00 = w38[9999];
  /* #111: @38 = func_acc10_acc10_acc10_acc10(@0) */
  arg1[0]=(&w00);
  res1[0]=w38;
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #112: output[0][39] = @38 */
  if (res[0]) casadi_copy(w38, 10000, res[0]+30000);
  /* #113: {NULL, @0} = horzsplit(@38) */
  w00 = w38[9999];
  /* #114: @38 = func_acc10_acc10_acc10_acc10(@0) */
  arg1[0]=(&w00);
  res1[0]=w38;
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #115: output[0][40] = @38 */
  if (res[0]) casadi_copy(w38, 10000, res[0]+40000);
  /* #116: {NULL, @0} = horzsplit(@38) */
  w00 = w38[9999];
  /* #117: @38 = func_acc10_acc10_acc10_acc10(@0) */
  arg1[0]=(&w00);
  res1[0]=w38;
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #118: output[0][41] = @38 */
  if (res[0]) casadi_copy(w38, 10000, res[0]+50000);
  /* #119: {NULL, @0} = horzsplit(@38) */
  w00 = w38[9999];
  /* #120: @38 = func_acc10_acc10_acc10_acc10(@0) */
  arg1[0]=(&w00);
  res1[0]=w38;
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #121: output[0][42] = @38 */
  if (res[0]) casadi_copy(w38, 10000, res[0]+60000);
  /* #122: {NULL, @0} = horzsplit(@38) */
  w00 = w38[9999];
  /* #123: @38 = func_acc10_acc10_acc10_acc10(@0) */
  arg1[0]=(&w00);
  res1[0]=w38;
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #124: output[0][43] = @38 */
  if (res[0]) casadi_copy(w38, 10000, res[0]+70000);
  /* #125: {NULL, @0} = horzsplit(@38) */
  w00 = w38[9999];
  /* #126: @38 = func_acc10_acc10_acc10_acc10(@0) */
  arg1[0]=(&w00);
  res1[0]=w38;
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #127: output[0][44] = @38 */
  if (res[0]) casadi_copy(w38, 10000, res[0]+80000);
  /* #128: {NULL, @0} = horzsplit(@38) */
  w00 = w38[9999];
  /* #129: @38 = func_acc10_acc10_acc10_acc10(@0) */
  arg1[0]=(&w00);
  res1[0]=w38;
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #130: output[0][45] = @38 */
  if (res[0]) casadi_copy(w38, 10000, res[0]+90000);
  return 0;
}

/* func_acc10_acc10_acc10_acc10_acc10_acc10:(x0)->(x1[1x1000000]) */
static int casadi_f7(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real **res1=res+1, *rr, w00, w01, w02, w03, w04, w05, w06, w07, w08, w09;
  casadi_real *w10=w+22228, w11, *w12=w+22239, *w13=w+22249, *w14=w+22259, *w15=w+22269, *w16=w+22279, *w17=w+22289, *w18=w+22299, *w19=w+22309, *w20=w+22319, *w21=w+22419;
  casadi_real *w22=w+22519, *w23=w+22619, *w24=w+22719, *w25=w+22819, *w26=w+22919, *w27=w+23019, *w28=w+23119, *w29=w+23219, *w30=w+24219, *w31=w+25219, *w32=w+26219, *w33=w+27219;
  casadi_real *w34=w+28219, *w35=w+29219, *w36=w+30219, *w37=w+31219, *w38=w+32219, *w39=w+42219, *w40=w+52219, *w41=w+62219, *w42=w+72219, *w43=w+82219, *w44=w+92219, *w45=w+102219;
  casadi_real *w46=w+112219, *w47=w+122219;
  const casadi_real **arg1=arg+1, *cs;
  /* #0: @0 = input[0][0] */
  w00 = arg[0] ? arg[0][0] : 0;
  /* #1: @0 = sin(@0) */
  w00 = sin( w00 );
  /* #2: output[0][0] = @0 */
  if (res[0]) res[0][0] = w00;
  /* #3: @1 = func(@0) */
  arg1[0]=(&w00);
  res1[0]=(&w01);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #4: output[0][1] = @1 */
  if (res[0]) res[0][1] = w01;
  /* #5: @2 = func(@1) */
  arg1[0]=(&w01);
  res1[0]=(&w02);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #6: output[0][2] = @2 */
  if (res[0]) res[0][2] = w02;
  /* #7: @3 = func(@2) */
  arg1[0]=(&w02);
  res1[0]=(&w03);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #8: output[0][3] = @3 */
  if (res[0]) res[0][3] = w03;
  /* #9: @4 = func(@3) */
  arg1[0]=(&w03);
  res1[0]=(&w04);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #10: output[0][4] = @4 */
  if (res[0]) res[0][4] = w04;
  /* #11: @5 = func(@4) */
  arg1[0]=(&w04);
  res1[0]=(&w05);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #12: output[0][5] = @5 */
  if (res[0]) res[0][5] = w05;
  /* #13: @6 = func(@5) */
  arg1[0]=(&w05);
  res1[0]=(&w06);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #14: output[0][6] = @6 */
  if (res[0]) res[0][6] = w06;
  /* #15: @7 = func(@6) */
  arg1[0]=(&w06);
  res1[0]=(&w07);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #16: output[0][7] = @7 */
  if (res[0]) res[0][7] = w07;
  /* #17: @8 = func(@7) */
  arg1[0]=(&w07);
  res1[0]=(&w08);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #18: output[0][8] = @8 */
  if (res[0]) res[0][8] = w08;
  /* #19: @9 = func(@8) */
  arg1[0]=(&w08);
  res1[0]=(&w09);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #20: output[0][9] = @9 */
  if (res[0]) res[0][9] = w09;
  /* #21: @10 = func_acc10(@9) */
  arg1[0]=(&w09);
  res1[0]=w10;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #22: output[0][10] = @10 */
  if (res[0]) casadi_copy(w10, 10, res[0]+10);
  /* #23: {NULL, @11} = horzsplit(@10) */
  w11 = w10[9];
  /* #24: @12 = func_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w12;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #25: output[0][11] = @12 */
  if (res[0]) casadi_copy(w12, 10, res[0]+20);
  /* #26: {NULL, @11} = horzsplit(@12) */
  w11 = w12[9];
  /* #27: @13 = func_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w13;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #28: output[0][12] = @13 */
  if (res[0]) casadi_copy(w13, 10, res[0]+30);
  /* #29: {NULL, @11} = horzsplit(@13) */
  w11 = w13[9];
  /* #30: @14 = func_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w14;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #31: output[0][13] = @14 */
  if (res[0]) casadi_copy(w14, 10, res[0]+40);
  /* #32: {NULL, @11} = horzsplit(@14) */
  w11 = w14[9];
  /* #33: @15 = func_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w15;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #34: output[0][14] = @15 */
  if (res[0]) casadi_copy(w15, 10, res[0]+50);
  /* #35: {NULL, @11} = horzsplit(@15) */
  w11 = w15[9];
  /* #36: @16 = func_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w16;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #37: output[0][15] = @16 */
  if (res[0]) casadi_copy(w16, 10, res[0]+60);
  /* #38: {NULL, @11} = horzsplit(@16) */
  w11 = w16[9];
  /* #39: @17 = func_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w17;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #40: output[0][16] = @17 */
  if (res[0]) casadi_copy(w17, 10, res[0]+70);
  /* #41: {NULL, @11} = horzsplit(@17) */
  w11 = w17[9];
  /* #42: @18 = func_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w18;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #43: output[0][17] = @18 */
  if (res[0]) casadi_copy(w18, 10, res[0]+80);
  /* #44: {NULL, @11} = horzsplit(@18) */
  w11 = w18[9];
  /* #45: @19 = func_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w19;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #46: output[0][18] = @19 */
  if (res[0]) casadi_copy(w19, 10, res[0]+90);
  /* #47: @20 = horzcat(@0, @1, @2, @3, @4, @5, @6, @7, @8, @9, @10, @12, @13, @14, @15, @16, @17, @18, @19) */
  rr=w20;
  *rr++ = w00;
  *rr++ = w01;
  *rr++ = w02;
  *rr++ = w03;
  *rr++ = w04;
  *rr++ = w05;
  *rr++ = w06;
  *rr++ = w07;
  *rr++ = w08;
  *rr++ = w09;
  for (i=0, cs=w10; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w12; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w13; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w14; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w15; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w16; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w17; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w18; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w19; i<10; ++i) *rr++ = *cs++;
  /* #48: {NULL, @11} = horzsplit(@20) */
  w11 = w20[99];
  /* #49: @20 = func_acc10_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w20;
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #50: output[0][19] = @20 */
  if (res[0]) casadi_copy(w20, 100, res[0]+100);
  /* #51: {NULL, @11} = horzsplit(@20) */
  w11 = w20[99];
  /* #52: @21 = func_acc10_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w21;
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #53: output[0][20] = @21 */
  if (res[0]) casadi_copy(w21, 100, res[0]+200);
  /* #54: {NULL, @11} = horzsplit(@21) */
  w11 = w21[99];
  /* #55: @22 = func_acc10_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w22;
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #56: output[0][21] = @22 */
  if (res[0]) casadi_copy(w22, 100, res[0]+300);
  /* #57: {NULL, @11} = horzsplit(@22) */
  w11 = w22[99];
  /* #58: @23 = func_acc10_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w23;
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #59: output[0][22] = @23 */
  if (res[0]) casadi_copy(w23, 100, res[0]+400);
  /* #60: {NULL, @11} = horzsplit(@23) */
  w11 = w23[99];
  /* #61: @24 = func_acc10_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w24;
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #62: output[0][23] = @24 */
  if (res[0]) casadi_copy(w24, 100, res[0]+500);
  /* #63: {NULL, @11} = horzsplit(@24) */
  w11 = w24[99];
  /* #64: @25 = func_acc10_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w25;
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #65: output[0][24] = @25 */
  if (res[0]) casadi_copy(w25, 100, res[0]+600);
  /* #66: {NULL, @11} = horzsplit(@25) */
  w11 = w25[99];
  /* #67: @26 = func_acc10_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w26;
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #68: output[0][25] = @26 */
  if (res[0]) casadi_copy(w26, 100, res[0]+700);
  /* #69: {NULL, @11} = horzsplit(@26) */
  w11 = w26[99];
  /* #70: @27 = func_acc10_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w27;
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #71: output[0][26] = @27 */
  if (res[0]) casadi_copy(w27, 100, res[0]+800);
  /* #72: {NULL, @11} = horzsplit(@27) */
  w11 = w27[99];
  /* #73: @28 = func_acc10_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w28;
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #74: output[0][27] = @28 */
  if (res[0]) casadi_copy(w28, 100, res[0]+900);
  /* #75: @29 = horzcat(@0, @1, @2, @3, @4, @5, @6, @7, @8, @9, @10, @12, @13, @14, @15, @16, @17, @18, @19, @20, @21, @22, @23, @24, @25, @26, @27, @28) */
  rr=w29;
  *rr++ = w00;
  *rr++ = w01;
  *rr++ = w02;
  *rr++ = w03;
  *rr++ = w04;
  *rr++ = w05;
  *rr++ = w06;
  *rr++ = w07;
  *rr++ = w08;
  *rr++ = w09;
  for (i=0, cs=w10; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w12; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w13; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w14; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w15; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w16; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w17; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w18; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w19; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w20; i<100; ++i) *rr++ = *cs++;
  for (i=0, cs=w21; i<100; ++i) *rr++ = *cs++;
  for (i=0, cs=w22; i<100; ++i) *rr++ = *cs++;
  for (i=0, cs=w23; i<100; ++i) *rr++ = *cs++;
  for (i=0, cs=w24; i<100; ++i) *rr++ = *cs++;
  for (i=0, cs=w25; i<100; ++i) *rr++ = *cs++;
  for (i=0, cs=w26; i<100; ++i) *rr++ = *cs++;
  for (i=0, cs=w27; i<100; ++i) *rr++ = *cs++;
  for (i=0, cs=w28; i<100; ++i) *rr++ = *cs++;
  /* #76: {NULL, @11} = horzsplit(@29) */
  w11 = w29[999];
  /* #77: @29 = func_acc10_acc10_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w29;
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #78: output[0][28] = @29 */
  if (res[0]) casadi_copy(w29, 1000, res[0]+1000);
  /* #79: {NULL, @11} = horzsplit(@29) */
  w11 = w29[999];
  /* #80: @30 = func_acc10_acc10_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w30;
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #81: output[0][29] = @30 */
  if (res[0]) casadi_copy(w30, 1000, res[0]+2000);
  /* #82: {NULL, @11} = horzsplit(@30) */
  w11 = w30[999];
  /* #83: @31 = func_acc10_acc10_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w31;
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #84: output[0][30] = @31 */
  if (res[0]) casadi_copy(w31, 1000, res[0]+3000);
  /* #85: {NULL, @11} = horzsplit(@31) */
  w11 = w31[999];
  /* #86: @32 = func_acc10_acc10_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w32;
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #87: output[0][31] = @32 */
  if (res[0]) casadi_copy(w32, 1000, res[0]+4000);
  /* #88: {NULL, @11} = horzsplit(@32) */
  w11 = w32[999];
  /* #89: @33 = func_acc10_acc10_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w33;
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #90: output[0][32] = @33 */
  if (res[0]) casadi_copy(w33, 1000, res[0]+5000);
  /* #91: {NULL, @11} = horzsplit(@33) */
  w11 = w33[999];
  /* #92: @34 = func_acc10_acc10_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w34;
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #93: output[0][33] = @34 */
  if (res[0]) casadi_copy(w34, 1000, res[0]+6000);
  /* #94: {NULL, @11} = horzsplit(@34) */
  w11 = w34[999];
  /* #95: @35 = func_acc10_acc10_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w35;
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #96: output[0][34] = @35 */
  if (res[0]) casadi_copy(w35, 1000, res[0]+7000);
  /* #97: {NULL, @11} = horzsplit(@35) */
  w11 = w35[999];
  /* #98: @36 = func_acc10_acc10_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w36;
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #99: output[0][35] = @36 */
  if (res[0]) casadi_copy(w36, 1000, res[0]+8000);
  /* #100: {NULL, @11} = horzsplit(@36) */
  w11 = w36[999];
  /* #101: @37 = func_acc10_acc10_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w37;
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #102: output[0][36] = @37 */
  if (res[0]) casadi_copy(w37, 1000, res[0]+9000);
  /* #103: @38 = horzcat(@0, @1, @2, @3, @4, @5, @6, @7, @8, @9, @10, @12, @13, @14, @15, @16, @17, @18, @19, @20, @21, @22, @23, @24, @25, @26, @27, @28, @29, @30, @31, @32, @33, @34, @35, @36, @37) */
  rr=w38;
  *rr++ = w00;
  *rr++ = w01;
  *rr++ = w02;
  *rr++ = w03;
  *rr++ = w04;
  *rr++ = w05;
  *rr++ = w06;
  *rr++ = w07;
  *rr++ = w08;
  *rr++ = w09;
  for (i=0, cs=w10; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w12; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w13; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w14; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w15; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w16; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w17; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w18; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w19; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w20; i<100; ++i) *rr++ = *cs++;
  for (i=0, cs=w21; i<100; ++i) *rr++ = *cs++;
  for (i=0, cs=w22; i<100; ++i) *rr++ = *cs++;
  for (i=0, cs=w23; i<100; ++i) *rr++ = *cs++;
  for (i=0, cs=w24; i<100; ++i) *rr++ = *cs++;
  for (i=0, cs=w25; i<100; ++i) *rr++ = *cs++;
  for (i=0, cs=w26; i<100; ++i) *rr++ = *cs++;
  for (i=0, cs=w27; i<100; ++i) *rr++ = *cs++;
  for (i=0, cs=w28; i<100; ++i) *rr++ = *cs++;
  for (i=0, cs=w29; i<1000; ++i) *rr++ = *cs++;
  for (i=0, cs=w30; i<1000; ++i) *rr++ = *cs++;
  for (i=0, cs=w31; i<1000; ++i) *rr++ = *cs++;
  for (i=0, cs=w32; i<1000; ++i) *rr++ = *cs++;
  for (i=0, cs=w33; i<1000; ++i) *rr++ = *cs++;
  for (i=0, cs=w34; i<1000; ++i) *rr++ = *cs++;
  for (i=0, cs=w35; i<1000; ++i) *rr++ = *cs++;
  for (i=0, cs=w36; i<1000; ++i) *rr++ = *cs++;
  for (i=0, cs=w37; i<1000; ++i) *rr++ = *cs++;
  /* #104: {NULL, @11} = horzsplit(@38) */
  w11 = w38[9999];
  /* #105: @38 = func_acc10_acc10_acc10_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w38;
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #106: output[0][37] = @38 */
  if (res[0]) casadi_copy(w38, 10000, res[0]+10000);
  /* #107: {NULL, @11} = horzsplit(@38) */
  w11 = w38[9999];
  /* #108: @39 = func_acc10_acc10_acc10_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w39;
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #109: output[0][38] = @39 */
  if (res[0]) casadi_copy(w39, 10000, res[0]+20000);
  /* #110: {NULL, @11} = horzsplit(@39) */
  w11 = w39[9999];
  /* #111: @40 = func_acc10_acc10_acc10_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w40;
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #112: output[0][39] = @40 */
  if (res[0]) casadi_copy(w40, 10000, res[0]+30000);
  /* #113: {NULL, @11} = horzsplit(@40) */
  w11 = w40[9999];
  /* #114: @41 = func_acc10_acc10_acc10_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w41;
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #115: output[0][40] = @41 */
  if (res[0]) casadi_copy(w41, 10000, res[0]+40000);
  /* #116: {NULL, @11} = horzsplit(@41) */
  w11 = w41[9999];
  /* #117: @42 = func_acc10_acc10_acc10_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w42;
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #118: output[0][41] = @42 */
  if (res[0]) casadi_copy(w42, 10000, res[0]+50000);
  /* #119: {NULL, @11} = horzsplit(@42) */
  w11 = w42[9999];
  /* #120: @43 = func_acc10_acc10_acc10_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w43;
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #121: output[0][42] = @43 */
  if (res[0]) casadi_copy(w43, 10000, res[0]+60000);
  /* #122: {NULL, @11} = horzsplit(@43) */
  w11 = w43[9999];
  /* #123: @44 = func_acc10_acc10_acc10_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w44;
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #124: output[0][43] = @44 */
  if (res[0]) casadi_copy(w44, 10000, res[0]+70000);
  /* #125: {NULL, @11} = horzsplit(@44) */
  w11 = w44[9999];
  /* #126: @45 = func_acc10_acc10_acc10_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w45;
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #127: output[0][44] = @45 */
  if (res[0]) casadi_copy(w45, 10000, res[0]+80000);
  /* #128: {NULL, @11} = horzsplit(@45) */
  w11 = w45[9999];
  /* #129: @46 = func_acc10_acc10_acc10_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w46;
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #130: output[0][45] = @46 */
  if (res[0]) casadi_copy(w46, 10000, res[0]+90000);
  /* #131: @47 = horzcat(@0, @1, @2, @3, @4, @5, @6, @7, @8, @9, @10, @12, @13, @14, @15, @16, @17, @18, @19, @20, @21, @22, @23, @24, @25, @26, @27, @28, @29, @30, @31, @32, @33, @34, @35, @36, @37, @38, @39, @40, @41, @42, @43, @44, @45, @46) */
  rr=w47;
  *rr++ = w00;
  *rr++ = w01;
  *rr++ = w02;
  *rr++ = w03;
  *rr++ = w04;
  *rr++ = w05;
  *rr++ = w06;
  *rr++ = w07;
  *rr++ = w08;
  *rr++ = w09;
  for (i=0, cs=w10; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w12; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w13; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w14; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w15; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w16; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w17; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w18; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w19; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w20; i<100; ++i) *rr++ = *cs++;
  for (i=0, cs=w21; i<100; ++i) *rr++ = *cs++;
  for (i=0, cs=w22; i<100; ++i) *rr++ = *cs++;
  for (i=0, cs=w23; i<100; ++i) *rr++ = *cs++;
  for (i=0, cs=w24; i<100; ++i) *rr++ = *cs++;
  for (i=0, cs=w25; i<100; ++i) *rr++ = *cs++;
  for (i=0, cs=w26; i<100; ++i) *rr++ = *cs++;
  for (i=0, cs=w27; i<100; ++i) *rr++ = *cs++;
  for (i=0, cs=w28; i<100; ++i) *rr++ = *cs++;
  for (i=0, cs=w29; i<1000; ++i) *rr++ = *cs++;
  for (i=0, cs=w30; i<1000; ++i) *rr++ = *cs++;
  for (i=0, cs=w31; i<1000; ++i) *rr++ = *cs++;
  for (i=0, cs=w32; i<1000; ++i) *rr++ = *cs++;
  for (i=0, cs=w33; i<1000; ++i) *rr++ = *cs++;
  for (i=0, cs=w34; i<1000; ++i) *rr++ = *cs++;
  for (i=0, cs=w35; i<1000; ++i) *rr++ = *cs++;
  for (i=0, cs=w36; i<1000; ++i) *rr++ = *cs++;
  for (i=0, cs=w37; i<1000; ++i) *rr++ = *cs++;
  for (i=0, cs=w38; i<10000; ++i) *rr++ = *cs++;
  for (i=0, cs=w39; i<10000; ++i) *rr++ = *cs++;
  for (i=0, cs=w40; i<10000; ++i) *rr++ = *cs++;
  for (i=0, cs=w41; i<10000; ++i) *rr++ = *cs++;
  for (i=0, cs=w42; i<10000; ++i) *rr++ = *cs++;
  for (i=0, cs=w43; i<10000; ++i) *rr++ = *cs++;
  for (i=0, cs=w44; i<10000; ++i) *rr++ = *cs++;
  for (i=0, cs=w45; i<10000; ++i) *rr++ = *cs++;
  for (i=0, cs=w46; i<10000; ++i) *rr++ = *cs++;
  /* #132: {NULL, @0} = horzsplit(@47) */
  w00 = w47[99999];
  /* #133: @47 = func_acc10_acc10_acc10_acc10_acc10(@0) */
  arg1[0]=(&w00);
  res1[0]=w47;
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #134: output[0][46] = @47 */
  if (res[0]) casadi_copy(w47, 100000, res[0]+100000);
  /* #135: {NULL, @0} = horzsplit(@47) */
  w00 = w47[99999];
  /* #136: @47 = func_acc10_acc10_acc10_acc10_acc10(@0) */
  arg1[0]=(&w00);
  res1[0]=w47;
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #137: output[0][47] = @47 */
  if (res[0]) casadi_copy(w47, 100000, res[0]+200000);
  /* #138: {NULL, @0} = horzsplit(@47) */
  w00 = w47[99999];
  /* #139: @47 = func_acc10_acc10_acc10_acc10_acc10(@0) */
  arg1[0]=(&w00);
  res1[0]=w47;
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #140: output[0][48] = @47 */
  if (res[0]) casadi_copy(w47, 100000, res[0]+300000);
  /* #141: {NULL, @0} = horzsplit(@47) */
  w00 = w47[99999];
  /* #142: @47 = func_acc10_acc10_acc10_acc10_acc10(@0) */
  arg1[0]=(&w00);
  res1[0]=w47;
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #143: output[0][49] = @47 */
  if (res[0]) casadi_copy(w47, 100000, res[0]+400000);
  /* #144: {NULL, @0} = horzsplit(@47) */
  w00 = w47[99999];
  /* #145: @47 = func_acc10_acc10_acc10_acc10_acc10(@0) */
  arg1[0]=(&w00);
  res1[0]=w47;
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #146: output[0][50] = @47 */
  if (res[0]) casadi_copy(w47, 100000, res[0]+500000);
  /* #147: {NULL, @0} = horzsplit(@47) */
  w00 = w47[99999];
  /* #148: @47 = func_acc10_acc10_acc10_acc10_acc10(@0) */
  arg1[0]=(&w00);
  res1[0]=w47;
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #149: output[0][51] = @47 */
  if (res[0]) casadi_copy(w47, 100000, res[0]+600000);
  /* #150: {NULL, @0} = horzsplit(@47) */
  w00 = w47[99999];
  /* #151: @47 = func_acc10_acc10_acc10_acc10_acc10(@0) */
  arg1[0]=(&w00);
  res1[0]=w47;
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #152: output[0][52] = @47 */
  if (res[0]) casadi_copy(w47, 100000, res[0]+700000);
  /* #153: {NULL, @0} = horzsplit(@47) */
  w00 = w47[99999];
  /* #154: @47 = func_acc10_acc10_acc10_acc10_acc10(@0) */
  arg1[0]=(&w00);
  res1[0]=w47;
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #155: output[0][53] = @47 */
  if (res[0]) casadi_copy(w47, 100000, res[0]+800000);
  /* #156: {NULL, @0} = horzsplit(@47) */
  w00 = w47[99999];
  /* #157: @47 = func_acc10_acc10_acc10_acc10_acc10(@0) */
  arg1[0]=(&w00);
  res1[0]=w47;
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #158: output[0][54] = @47 */
  if (res[0]) casadi_copy(w47, 100000, res[0]+900000);
  return 0;
}

/* fold_func:(x0)->(x1) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real **res1=res+1, *rr, w00, w01, w02, w03, w04, w05, w06, w07, w08, w09;
  casadi_real *w10=w+222229, w11, *w12=w+222240, *w13=w+222250, *w14=w+222260, *w15=w+222270, *w16=w+222280, *w17=w+222290, *w18=w+222300, *w19=w+222310, *w20=w+222320, *w21=w+222420;
  casadi_real *w22=w+222520, *w23=w+222620, *w24=w+222720, *w25=w+222820, *w26=w+222920, *w27=w+223020, *w28=w+223120, *w29=w+223220, *w30=w+224220, *w31=w+225220, *w32=w+226220, *w33=w+227220;
  casadi_real *w34=w+228220, *w35=w+229220, *w36=w+230220, *w37=w+231220, *w38=w+232220, *w39=w+242220, *w40=w+252220, *w41=w+262220, *w42=w+272220, *w43=w+282220, *w44=w+292220, *w45=w+302220;
  casadi_real *w46=w+312220, *w47=w+322220, *w48=w+422220, *w49=w+522220, *w50=w+622220, *w51=w+722220, *w52=w+822220, *w53=w+922220, *w54=w+1022220, *w55=w+1122220, *w56=w+1222220;
  const casadi_real **arg1=arg+1, *cs;
  /* #0: @0 = input[0][0] */
  w00 = arg[0] ? arg[0][0] : 0;
  /* #1: @0 = sin(@0) */
  w00 = sin( w00 );
  /* #2: @1 = func(@0) */
  arg1[0]=(&w00);
  res1[0]=(&w01);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #3: @2 = func(@1) */
  arg1[0]=(&w01);
  res1[0]=(&w02);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #4: @3 = func(@2) */
  arg1[0]=(&w02);
  res1[0]=(&w03);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #5: @4 = func(@3) */
  arg1[0]=(&w03);
  res1[0]=(&w04);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #6: @5 = func(@4) */
  arg1[0]=(&w04);
  res1[0]=(&w05);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #7: @6 = func(@5) */
  arg1[0]=(&w05);
  res1[0]=(&w06);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #8: @7 = func(@6) */
  arg1[0]=(&w06);
  res1[0]=(&w07);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #9: @8 = func(@7) */
  arg1[0]=(&w07);
  res1[0]=(&w08);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #10: @9 = func(@8) */
  arg1[0]=(&w08);
  res1[0]=(&w09);
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #11: @10 = func_acc10(@9) */
  arg1[0]=(&w09);
  res1[0]=w10;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #12: {NULL, @11} = horzsplit(@10) */
  w11 = w10[9];
  /* #13: @12 = func_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w12;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #14: {NULL, @11} = horzsplit(@12) */
  w11 = w12[9];
  /* #15: @13 = func_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w13;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #16: {NULL, @11} = horzsplit(@13) */
  w11 = w13[9];
  /* #17: @14 = func_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w14;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #18: {NULL, @11} = horzsplit(@14) */
  w11 = w14[9];
  /* #19: @15 = func_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w15;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #20: {NULL, @11} = horzsplit(@15) */
  w11 = w15[9];
  /* #21: @16 = func_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w16;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #22: {NULL, @11} = horzsplit(@16) */
  w11 = w16[9];
  /* #23: @17 = func_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w17;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #24: {NULL, @11} = horzsplit(@17) */
  w11 = w17[9];
  /* #25: @18 = func_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w18;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #26: {NULL, @11} = horzsplit(@18) */
  w11 = w18[9];
  /* #27: @19 = func_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w19;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #28: @20 = horzcat(@0, @1, @2, @3, @4, @5, @6, @7, @8, @9, @10, @12, @13, @14, @15, @16, @17, @18, @19) */
  rr=w20;
  *rr++ = w00;
  *rr++ = w01;
  *rr++ = w02;
  *rr++ = w03;
  *rr++ = w04;
  *rr++ = w05;
  *rr++ = w06;
  *rr++ = w07;
  *rr++ = w08;
  *rr++ = w09;
  for (i=0, cs=w10; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w12; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w13; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w14; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w15; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w16; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w17; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w18; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w19; i<10; ++i) *rr++ = *cs++;
  /* #29: {NULL, @11} = horzsplit(@20) */
  w11 = w20[99];
  /* #30: @20 = func_acc10_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w20;
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #31: {NULL, @11} = horzsplit(@20) */
  w11 = w20[99];
  /* #32: @21 = func_acc10_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w21;
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #33: {NULL, @11} = horzsplit(@21) */
  w11 = w21[99];
  /* #34: @22 = func_acc10_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w22;
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #35: {NULL, @11} = horzsplit(@22) */
  w11 = w22[99];
  /* #36: @23 = func_acc10_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w23;
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #37: {NULL, @11} = horzsplit(@23) */
  w11 = w23[99];
  /* #38: @24 = func_acc10_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w24;
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #39: {NULL, @11} = horzsplit(@24) */
  w11 = w24[99];
  /* #40: @25 = func_acc10_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w25;
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #41: {NULL, @11} = horzsplit(@25) */
  w11 = w25[99];
  /* #42: @26 = func_acc10_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w26;
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #43: {NULL, @11} = horzsplit(@26) */
  w11 = w26[99];
  /* #44: @27 = func_acc10_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w27;
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #45: {NULL, @11} = horzsplit(@27) */
  w11 = w27[99];
  /* #46: @28 = func_acc10_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w28;
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #47: @29 = horzcat(@0, @1, @2, @3, @4, @5, @6, @7, @8, @9, @10, @12, @13, @14, @15, @16, @17, @18, @19, @20, @21, @22, @23, @24, @25, @26, @27, @28) */
  rr=w29;
  *rr++ = w00;
  *rr++ = w01;
  *rr++ = w02;
  *rr++ = w03;
  *rr++ = w04;
  *rr++ = w05;
  *rr++ = w06;
  *rr++ = w07;
  *rr++ = w08;
  *rr++ = w09;
  for (i=0, cs=w10; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w12; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w13; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w14; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w15; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w16; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w17; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w18; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w19; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w20; i<100; ++i) *rr++ = *cs++;
  for (i=0, cs=w21; i<100; ++i) *rr++ = *cs++;
  for (i=0, cs=w22; i<100; ++i) *rr++ = *cs++;
  for (i=0, cs=w23; i<100; ++i) *rr++ = *cs++;
  for (i=0, cs=w24; i<100; ++i) *rr++ = *cs++;
  for (i=0, cs=w25; i<100; ++i) *rr++ = *cs++;
  for (i=0, cs=w26; i<100; ++i) *rr++ = *cs++;
  for (i=0, cs=w27; i<100; ++i) *rr++ = *cs++;
  for (i=0, cs=w28; i<100; ++i) *rr++ = *cs++;
  /* #48: {NULL, @11} = horzsplit(@29) */
  w11 = w29[999];
  /* #49: @29 = func_acc10_acc10_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w29;
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #50: {NULL, @11} = horzsplit(@29) */
  w11 = w29[999];
  /* #51: @30 = func_acc10_acc10_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w30;
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #52: {NULL, @11} = horzsplit(@30) */
  w11 = w30[999];
  /* #53: @31 = func_acc10_acc10_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w31;
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #54: {NULL, @11} = horzsplit(@31) */
  w11 = w31[999];
  /* #55: @32 = func_acc10_acc10_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w32;
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #56: {NULL, @11} = horzsplit(@32) */
  w11 = w32[999];
  /* #57: @33 = func_acc10_acc10_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w33;
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #58: {NULL, @11} = horzsplit(@33) */
  w11 = w33[999];
  /* #59: @34 = func_acc10_acc10_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w34;
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #60: {NULL, @11} = horzsplit(@34) */
  w11 = w34[999];
  /* #61: @35 = func_acc10_acc10_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w35;
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #62: {NULL, @11} = horzsplit(@35) */
  w11 = w35[999];
  /* #63: @36 = func_acc10_acc10_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w36;
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #64: {NULL, @11} = horzsplit(@36) */
  w11 = w36[999];
  /* #65: @37 = func_acc10_acc10_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w37;
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #66: @38 = horzcat(@0, @1, @2, @3, @4, @5, @6, @7, @8, @9, @10, @12, @13, @14, @15, @16, @17, @18, @19, @20, @21, @22, @23, @24, @25, @26, @27, @28, @29, @30, @31, @32, @33, @34, @35, @36, @37) */
  rr=w38;
  *rr++ = w00;
  *rr++ = w01;
  *rr++ = w02;
  *rr++ = w03;
  *rr++ = w04;
  *rr++ = w05;
  *rr++ = w06;
  *rr++ = w07;
  *rr++ = w08;
  *rr++ = w09;
  for (i=0, cs=w10; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w12; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w13; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w14; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w15; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w16; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w17; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w18; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w19; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w20; i<100; ++i) *rr++ = *cs++;
  for (i=0, cs=w21; i<100; ++i) *rr++ = *cs++;
  for (i=0, cs=w22; i<100; ++i) *rr++ = *cs++;
  for (i=0, cs=w23; i<100; ++i) *rr++ = *cs++;
  for (i=0, cs=w24; i<100; ++i) *rr++ = *cs++;
  for (i=0, cs=w25; i<100; ++i) *rr++ = *cs++;
  for (i=0, cs=w26; i<100; ++i) *rr++ = *cs++;
  for (i=0, cs=w27; i<100; ++i) *rr++ = *cs++;
  for (i=0, cs=w28; i<100; ++i) *rr++ = *cs++;
  for (i=0, cs=w29; i<1000; ++i) *rr++ = *cs++;
  for (i=0, cs=w30; i<1000; ++i) *rr++ = *cs++;
  for (i=0, cs=w31; i<1000; ++i) *rr++ = *cs++;
  for (i=0, cs=w32; i<1000; ++i) *rr++ = *cs++;
  for (i=0, cs=w33; i<1000; ++i) *rr++ = *cs++;
  for (i=0, cs=w34; i<1000; ++i) *rr++ = *cs++;
  for (i=0, cs=w35; i<1000; ++i) *rr++ = *cs++;
  for (i=0, cs=w36; i<1000; ++i) *rr++ = *cs++;
  for (i=0, cs=w37; i<1000; ++i) *rr++ = *cs++;
  /* #67: {NULL, @11} = horzsplit(@38) */
  w11 = w38[9999];
  /* #68: @38 = func_acc10_acc10_acc10_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w38;
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #69: {NULL, @11} = horzsplit(@38) */
  w11 = w38[9999];
  /* #70: @39 = func_acc10_acc10_acc10_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w39;
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #71: {NULL, @11} = horzsplit(@39) */
  w11 = w39[9999];
  /* #72: @40 = func_acc10_acc10_acc10_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w40;
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #73: {NULL, @11} = horzsplit(@40) */
  w11 = w40[9999];
  /* #74: @41 = func_acc10_acc10_acc10_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w41;
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #75: {NULL, @11} = horzsplit(@41) */
  w11 = w41[9999];
  /* #76: @42 = func_acc10_acc10_acc10_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w42;
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #77: {NULL, @11} = horzsplit(@42) */
  w11 = w42[9999];
  /* #78: @43 = func_acc10_acc10_acc10_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w43;
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #79: {NULL, @11} = horzsplit(@43) */
  w11 = w43[9999];
  /* #80: @44 = func_acc10_acc10_acc10_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w44;
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #81: {NULL, @11} = horzsplit(@44) */
  w11 = w44[9999];
  /* #82: @45 = func_acc10_acc10_acc10_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w45;
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #83: {NULL, @11} = horzsplit(@45) */
  w11 = w45[9999];
  /* #84: @46 = func_acc10_acc10_acc10_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w46;
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #85: @47 = horzcat(@0, @1, @2, @3, @4, @5, @6, @7, @8, @9, @10, @12, @13, @14, @15, @16, @17, @18, @19, @20, @21, @22, @23, @24, @25, @26, @27, @28, @29, @30, @31, @32, @33, @34, @35, @36, @37, @38, @39, @40, @41, @42, @43, @44, @45, @46) */
  rr=w47;
  *rr++ = w00;
  *rr++ = w01;
  *rr++ = w02;
  *rr++ = w03;
  *rr++ = w04;
  *rr++ = w05;
  *rr++ = w06;
  *rr++ = w07;
  *rr++ = w08;
  *rr++ = w09;
  for (i=0, cs=w10; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w12; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w13; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w14; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w15; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w16; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w17; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w18; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w19; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w20; i<100; ++i) *rr++ = *cs++;
  for (i=0, cs=w21; i<100; ++i) *rr++ = *cs++;
  for (i=0, cs=w22; i<100; ++i) *rr++ = *cs++;
  for (i=0, cs=w23; i<100; ++i) *rr++ = *cs++;
  for (i=0, cs=w24; i<100; ++i) *rr++ = *cs++;
  for (i=0, cs=w25; i<100; ++i) *rr++ = *cs++;
  for (i=0, cs=w26; i<100; ++i) *rr++ = *cs++;
  for (i=0, cs=w27; i<100; ++i) *rr++ = *cs++;
  for (i=0, cs=w28; i<100; ++i) *rr++ = *cs++;
  for (i=0, cs=w29; i<1000; ++i) *rr++ = *cs++;
  for (i=0, cs=w30; i<1000; ++i) *rr++ = *cs++;
  for (i=0, cs=w31; i<1000; ++i) *rr++ = *cs++;
  for (i=0, cs=w32; i<1000; ++i) *rr++ = *cs++;
  for (i=0, cs=w33; i<1000; ++i) *rr++ = *cs++;
  for (i=0, cs=w34; i<1000; ++i) *rr++ = *cs++;
  for (i=0, cs=w35; i<1000; ++i) *rr++ = *cs++;
  for (i=0, cs=w36; i<1000; ++i) *rr++ = *cs++;
  for (i=0, cs=w37; i<1000; ++i) *rr++ = *cs++;
  for (i=0, cs=w38; i<10000; ++i) *rr++ = *cs++;
  for (i=0, cs=w39; i<10000; ++i) *rr++ = *cs++;
  for (i=0, cs=w40; i<10000; ++i) *rr++ = *cs++;
  for (i=0, cs=w41; i<10000; ++i) *rr++ = *cs++;
  for (i=0, cs=w42; i<10000; ++i) *rr++ = *cs++;
  for (i=0, cs=w43; i<10000; ++i) *rr++ = *cs++;
  for (i=0, cs=w44; i<10000; ++i) *rr++ = *cs++;
  for (i=0, cs=w45; i<10000; ++i) *rr++ = *cs++;
  for (i=0, cs=w46; i<10000; ++i) *rr++ = *cs++;
  /* #86: {NULL, @11} = horzsplit(@47) */
  w11 = w47[99999];
  /* #87: @47 = func_acc10_acc10_acc10_acc10_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w47;
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #88: {NULL, @11} = horzsplit(@47) */
  w11 = w47[99999];
  /* #89: @48 = func_acc10_acc10_acc10_acc10_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w48;
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #90: {NULL, @11} = horzsplit(@48) */
  w11 = w48[99999];
  /* #91: @49 = func_acc10_acc10_acc10_acc10_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w49;
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #92: {NULL, @11} = horzsplit(@49) */
  w11 = w49[99999];
  /* #93: @50 = func_acc10_acc10_acc10_acc10_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w50;
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #94: {NULL, @11} = horzsplit(@50) */
  w11 = w50[99999];
  /* #95: @51 = func_acc10_acc10_acc10_acc10_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w51;
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #96: {NULL, @11} = horzsplit(@51) */
  w11 = w51[99999];
  /* #97: @52 = func_acc10_acc10_acc10_acc10_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w52;
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #98: {NULL, @11} = horzsplit(@52) */
  w11 = w52[99999];
  /* #99: @53 = func_acc10_acc10_acc10_acc10_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w53;
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #100: {NULL, @11} = horzsplit(@53) */
  w11 = w53[99999];
  /* #101: @54 = func_acc10_acc10_acc10_acc10_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w54;
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #102: {NULL, @11} = horzsplit(@54) */
  w11 = w54[99999];
  /* #103: @55 = func_acc10_acc10_acc10_acc10_acc10(@11) */
  arg1[0]=(&w11);
  res1[0]=w55;
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #104: @56 = horzcat(@0, @1, @2, @3, @4, @5, @6, @7, @8, @9, @10, @12, @13, @14, @15, @16, @17, @18, @19, @20, @21, @22, @23, @24, @25, @26, @27, @28, @29, @30, @31, @32, @33, @34, @35, @36, @37, @38, @39, @40, @41, @42, @43, @44, @45, @46, @47, @48, @49, @50, @51, @52, @53, @54, @55) */
  rr=w56;
  *rr++ = w00;
  *rr++ = w01;
  *rr++ = w02;
  *rr++ = w03;
  *rr++ = w04;
  *rr++ = w05;
  *rr++ = w06;
  *rr++ = w07;
  *rr++ = w08;
  *rr++ = w09;
  for (i=0, cs=w10; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w12; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w13; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w14; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w15; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w16; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w17; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w18; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w19; i<10; ++i) *rr++ = *cs++;
  for (i=0, cs=w20; i<100; ++i) *rr++ = *cs++;
  for (i=0, cs=w21; i<100; ++i) *rr++ = *cs++;
  for (i=0, cs=w22; i<100; ++i) *rr++ = *cs++;
  for (i=0, cs=w23; i<100; ++i) *rr++ = *cs++;
  for (i=0, cs=w24; i<100; ++i) *rr++ = *cs++;
  for (i=0, cs=w25; i<100; ++i) *rr++ = *cs++;
  for (i=0, cs=w26; i<100; ++i) *rr++ = *cs++;
  for (i=0, cs=w27; i<100; ++i) *rr++ = *cs++;
  for (i=0, cs=w28; i<100; ++i) *rr++ = *cs++;
  for (i=0, cs=w29; i<1000; ++i) *rr++ = *cs++;
  for (i=0, cs=w30; i<1000; ++i) *rr++ = *cs++;
  for (i=0, cs=w31; i<1000; ++i) *rr++ = *cs++;
  for (i=0, cs=w32; i<1000; ++i) *rr++ = *cs++;
  for (i=0, cs=w33; i<1000; ++i) *rr++ = *cs++;
  for (i=0, cs=w34; i<1000; ++i) *rr++ = *cs++;
  for (i=0, cs=w35; i<1000; ++i) *rr++ = *cs++;
  for (i=0, cs=w36; i<1000; ++i) *rr++ = *cs++;
  for (i=0, cs=w37; i<1000; ++i) *rr++ = *cs++;
  for (i=0, cs=w38; i<10000; ++i) *rr++ = *cs++;
  for (i=0, cs=w39; i<10000; ++i) *rr++ = *cs++;
  for (i=0, cs=w40; i<10000; ++i) *rr++ = *cs++;
  for (i=0, cs=w41; i<10000; ++i) *rr++ = *cs++;
  for (i=0, cs=w42; i<10000; ++i) *rr++ = *cs++;
  for (i=0, cs=w43; i<10000; ++i) *rr++ = *cs++;
  for (i=0, cs=w44; i<10000; ++i) *rr++ = *cs++;
  for (i=0, cs=w45; i<10000; ++i) *rr++ = *cs++;
  for (i=0, cs=w46; i<10000; ++i) *rr++ = *cs++;
  for (i=0, cs=w47; i<100000; ++i) *rr++ = *cs++;
  for (i=0, cs=w48; i<100000; ++i) *rr++ = *cs++;
  for (i=0, cs=w49; i<100000; ++i) *rr++ = *cs++;
  for (i=0, cs=w50; i<100000; ++i) *rr++ = *cs++;
  for (i=0, cs=w51; i<100000; ++i) *rr++ = *cs++;
  for (i=0, cs=w52; i<100000; ++i) *rr++ = *cs++;
  for (i=0, cs=w53; i<100000; ++i) *rr++ = *cs++;
  for (i=0, cs=w54; i<100000; ++i) *rr++ = *cs++;
  for (i=0, cs=w55; i<100000; ++i) *rr++ = *cs++;
  /* #105: {NULL, @0} = horzsplit(@56) */
  w00 = w56[999999];
  /* #106: @56 = func_acc10_acc10_acc10_acc10_acc10_acc10(@0) */
  arg1[0]=(&w00);
  res1[0]=w56;
  if (casadi_f7(arg1, res1, iw, w, 0)) return 1;
  /* #107: {NULL, @0} = horzsplit(@56) */
  w00 = w56[999999];
  /* #108: @56 = func_acc10_acc10_acc10_acc10_acc10_acc10(@0) */
  arg1[0]=(&w00);
  res1[0]=w56;
  if (casadi_f7(arg1, res1, iw, w, 0)) return 1;
  /* #109: {NULL, @0} = horzsplit(@56) */
  w00 = w56[999999];
  /* #110: @56 = func_acc10_acc10_acc10_acc10_acc10_acc10(@0) */
  arg1[0]=(&w00);
  res1[0]=w56;
  if (casadi_f7(arg1, res1, iw, w, 0)) return 1;
  /* #111: {NULL, @0} = horzsplit(@56) */
  w00 = w56[999999];
  /* #112: @56 = func_acc10_acc10_acc10_acc10_acc10_acc10(@0) */
  arg1[0]=(&w00);
  res1[0]=w56;
  if (casadi_f7(arg1, res1, iw, w, 0)) return 1;
  /* #113: {NULL, @0} = horzsplit(@56) */
  w00 = w56[999999];
  /* #114: @56 = func_acc10_acc10_acc10_acc10_acc10_acc10(@0) */
  arg1[0]=(&w00);
  res1[0]=w56;
  if (casadi_f7(arg1, res1, iw, w, 0)) return 1;
  /* #115: {NULL, @0} = horzsplit(@56) */
  w00 = w56[999999];
  /* #116: @56 = func_acc10_acc10_acc10_acc10_acc10_acc10(@0) */
  arg1[0]=(&w00);
  res1[0]=w56;
  if (casadi_f7(arg1, res1, iw, w, 0)) return 1;
  /* #117: {NULL, @0} = horzsplit(@56) */
  w00 = w56[999999];
  /* #118: @56 = func_acc10_acc10_acc10_acc10_acc10_acc10(@0) */
  arg1[0]=(&w00);
  res1[0]=w56;
  if (casadi_f7(arg1, res1, iw, w, 0)) return 1;
  /* #119: {NULL, @0} = horzsplit(@56) */
  w00 = w56[999999];
  /* #120: @56 = func_acc10_acc10_acc10_acc10_acc10_acc10(@0) */
  arg1[0]=(&w00);
  res1[0]=w56;
  if (casadi_f7(arg1, res1, iw, w, 0)) return 1;
  /* #121: {NULL, @0} = horzsplit(@56) */
  w00 = w56[999999];
  /* #122: @56 = func_acc10_acc10_acc10_acc10_acc10_acc10(@0) */
  arg1[0]=(&w00);
  res1[0]=w56;
  if (casadi_f7(arg1, res1, iw, w, 0)) return 1;
  /* #123: @0 = @56[999999] */
  for (rr=(&w00), cs=w56+999999; cs!=w56+1000000; cs+=1) *rr++ = *cs;
  /* #124: output[0][0] = @0 */
  if (res[0]) res[0][0] = w00;
  return 0;
}

CASADI_SYMBOL_EXPORT int fold_func(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int fold_func_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int fold_func_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void fold_func_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int fold_func_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void fold_func_release(int mem) {
}

CASADI_SYMBOL_EXPORT void fold_func_incref(void) {
}

CASADI_SYMBOL_EXPORT void fold_func_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int fold_func_n_in(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_int fold_func_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real fold_func_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* fold_func_name_in(casadi_int i) {
  switch (i) {
    case 0: return "x0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* fold_func_name_out(casadi_int i) {
  switch (i) {
    case 0: return "x1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* fold_func_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* fold_func_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int fold_func_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 56;
  if (sz_res) *sz_res = 9;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 2222220;
  return 0;
}

CASADI_SYMBOL_EXPORT int fold_func_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 56*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 9*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 2222220*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
