/* This file was automatically generated by CasADi 3.8.0+.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) zcc_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_mtimes_dense CASADI_PREFIX(mtimes_dense)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s11 CASADI_PREFIX(s11)
#define casadi_s12 CASADI_PREFIX(s12)
#define casadi_s13 CASADI_PREFIX(s13)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_mtimes_dense(const casadi_real* x, casadi_int nrow_x, casadi_int ncol_x,
    const casadi_real* y, casadi_int ncol_y, casadi_real* z, casadi_int tr) {
  casadi_int i, j, k;
  if (tr) {
    for (i=0; i<ncol_y; ++i) {
      for (j=0; j<ncol_x; ++j) {
        for (k=0; k<nrow_x; ++k) {
          z[j + i*ncol_x] += x[k + j*nrow_x] * y[k + i*nrow_x];
        }
      }
    }
  } else {
    for (i=0; i<ncol_y; ++i) {
      for (j=0; j<nrow_x; ++j) {
        for (k=0; k<ncol_x; ++k) {
          z[j + i*nrow_x] += x[j + k*nrow_x] * y[k + i*ncol_x];
        }
      }
    }
  }
}

static const casadi_int casadi_s0[3] = {2, 1, 1};
static const casadi_int casadi_s1[3] = {3, 1, 1};
static const casadi_int casadi_s2[3] = {1, 1, 1};
static const casadi_int casadi_s3[4] = {1, 1, 0, 0};
static const casadi_int casadi_s4[3] = {1, 2, 1};
static const casadi_int casadi_s5[3] = {1, 3, 1};
static const casadi_int casadi_s6[5] = {1, 2, 0, 0, 0};
static const casadi_int casadi_s7[6] = {1, 3, 0, 0, 0, 0};
static const casadi_int casadi_s8[5] = {2, 2, 0, 0, 0};
static const casadi_int casadi_s9[6] = {2, 3, 0, 0, 0, 0};
static const casadi_int casadi_s10[4] = {2, 1, 0, 0};
static const casadi_int casadi_s11[5] = {3, 2, 0, 0, 0};
static const casadi_int casadi_s12[6] = {3, 3, 0, 0, 0, 0};
static const casadi_int casadi_s13[4] = {3, 1, 0, 0};

/* zcc:(x[2],y[3])->(z) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, *w1=w+1, *w2=w+3, w3, *w4=w+5, *w5=w+8;
  /* #0: @0 = 0 */
  w0 = 0.;
  /* #1: @1 = ones(1x2) */
  casadi_fill(w1, 2, 1.);
  /* #2: @2 = input[0][0] */
  casadi_copy(arg[0], 2, w2);
  /* #3: @0 = mac(@1,@2,@0) */
  casadi_mtimes_dense(w1, 1, 2, w2, 1, (&w0), 0);
  /* #4: @3 = 0 */
  w3 = 0.;
  /* #5: @4 = ones(1x3) */
  casadi_fill(w4, 3, 1.);
  /* #6: @5 = input[1][0] */
  casadi_copy(arg[1], 3, w5);
  /* #7: @3 = mac(@4,@5,@3) */
  casadi_mtimes_dense(w4, 1, 3, w5, 1, (&w3), 0);
  /* #8: @0 = (@0+@3) */
  w0 += w3;
  /* #9: output[0][0] = @0 */
  if (res[0]) res[0][0] = w0;
  return 0;
}

extern "C" CASADI_SYMBOL_EXPORT int zcc(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

extern "C" CASADI_SYMBOL_EXPORT int zcc_checkout(void) {
  return 0;
}

extern "C" CASADI_SYMBOL_EXPORT void zcc_release(int mem) {
}

extern "C" CASADI_SYMBOL_EXPORT void zcc_incref(void) {
}

extern "C" CASADI_SYMBOL_EXPORT void zcc_decref(void) {
}

extern "C" CASADI_SYMBOL_EXPORT casadi_int zcc_n_in(void) { return 2;}

extern "C" CASADI_SYMBOL_EXPORT casadi_int zcc_n_out(void) { return 1;}

extern "C" CASADI_SYMBOL_EXPORT casadi_real zcc_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

extern "C" CASADI_SYMBOL_EXPORT const char* zcc_name_in(casadi_int i) {
  switch (i) {
    case 0: return "x";
    case 1: return "y";
    default: return 0;
  }
}

extern "C" CASADI_SYMBOL_EXPORT const char* zcc_name_out(casadi_int i) {
  switch (i) {
    case 0: return "z";
    default: return 0;
  }
}

extern "C" CASADI_SYMBOL_EXPORT const casadi_int* zcc_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

extern "C" CASADI_SYMBOL_EXPORT const casadi_int* zcc_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    default: return 0;
  }
}

extern "C" CASADI_SYMBOL_EXPORT int zcc_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 11;
  return 0;
}

extern "C" CASADI_SYMBOL_EXPORT int zcc_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 11*sizeof(casadi_real);
  return 0;
}

/* jac_zcc:(x[2],y[3],out_z[1x1,0nz])->(jac_z_x[1x2],jac_z_y[1x3]) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *w0=w+0, *w1=w+5, *w2=w+7;
  /* #0: @0 = ones(1x5) */
  casadi_fill(w0, 5, 1.);
  /* #1: {@1, @2} = horzsplit(@0) */
  casadi_copy(w0, 2, w1);
  casadi_copy(w0+2, 3, w2);
  /* #2: output[0][0] = @1 */
  casadi_copy(w1, 2, res[0]);
  /* #3: output[1][0] = @2 */
  casadi_copy(w2, 3, res[1]);
  return 0;
}

extern "C" CASADI_SYMBOL_EXPORT int jac_zcc(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f1(arg, res, iw, w, mem);
}

extern "C" CASADI_SYMBOL_EXPORT int jac_zcc_checkout(void) {
  return 0;
}

extern "C" CASADI_SYMBOL_EXPORT void jac_zcc_release(int mem) {
}

extern "C" CASADI_SYMBOL_EXPORT void jac_zcc_incref(void) {
}

extern "C" CASADI_SYMBOL_EXPORT void jac_zcc_decref(void) {
}

extern "C" CASADI_SYMBOL_EXPORT casadi_int jac_zcc_n_in(void) { return 3;}

extern "C" CASADI_SYMBOL_EXPORT casadi_int jac_zcc_n_out(void) { return 2;}

extern "C" CASADI_SYMBOL_EXPORT casadi_real jac_zcc_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

extern "C" CASADI_SYMBOL_EXPORT const char* jac_zcc_name_in(casadi_int i) {
  switch (i) {
    case 0: return "x";
    case 1: return "y";
    case 2: return "out_z";
    default: return 0;
  }
}

extern "C" CASADI_SYMBOL_EXPORT const char* jac_zcc_name_out(casadi_int i) {
  switch (i) {
    case 0: return "jac_z_x";
    case 1: return "jac_z_y";
    default: return 0;
  }
}

extern "C" CASADI_SYMBOL_EXPORT const casadi_int* jac_zcc_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s3;
    default: return 0;
  }
}

extern "C" CASADI_SYMBOL_EXPORT const casadi_int* jac_zcc_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    default: return 0;
  }
}

extern "C" CASADI_SYMBOL_EXPORT int jac_zcc_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4;
  if (sz_res) *sz_res = 4;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 10;
  return 0;
}

extern "C" CASADI_SYMBOL_EXPORT int jac_zcc_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 4*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 4*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 10*sizeof(casadi_real);
  return 0;
}

/* jac_jac_zcc:(x[2],y[3],out_z[1x1,0nz],out_jac_z_x[1x2,0nz],out_jac_z_y[1x3,0nz])->(jac_jac_z_x_x[2x2,0nz],jac_jac_z_x_y[2x3,0nz],jac_jac_z_x_out_z[2x1,0nz],jac_jac_z_y_x[3x2,0nz],jac_jac_z_y_y[3x3,0nz],jac_jac_z_y_out_z[3x1,0nz]) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  return 0;
}

extern "C" CASADI_SYMBOL_EXPORT int jac_jac_zcc(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f2(arg, res, iw, w, mem);
}

extern "C" CASADI_SYMBOL_EXPORT int jac_jac_zcc_checkout(void) {
  return 0;
}

extern "C" CASADI_SYMBOL_EXPORT void jac_jac_zcc_release(int mem) {
}

extern "C" CASADI_SYMBOL_EXPORT void jac_jac_zcc_incref(void) {
}

extern "C" CASADI_SYMBOL_EXPORT void jac_jac_zcc_decref(void) {
}

extern "C" CASADI_SYMBOL_EXPORT casadi_int jac_jac_zcc_n_in(void) { return 5;}

extern "C" CASADI_SYMBOL_EXPORT casadi_int jac_jac_zcc_n_out(void) { return 6;}

extern "C" CASADI_SYMBOL_EXPORT casadi_real jac_jac_zcc_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

extern "C" CASADI_SYMBOL_EXPORT const char* jac_jac_zcc_name_in(casadi_int i) {
  switch (i) {
    case 0: return "x";
    case 1: return "y";
    case 2: return "out_z";
    case 3: return "out_jac_z_x";
    case 4: return "out_jac_z_y";
    default: return 0;
  }
}

extern "C" CASADI_SYMBOL_EXPORT const char* jac_jac_zcc_name_out(casadi_int i) {
  switch (i) {
    case 0: return "jac_jac_z_x_x";
    case 1: return "jac_jac_z_x_y";
    case 2: return "jac_jac_z_x_out_z";
    case 3: return "jac_jac_z_y_x";
    case 4: return "jac_jac_z_y_y";
    case 5: return "jac_jac_z_y_out_z";
    default: return 0;
  }
}

extern "C" CASADI_SYMBOL_EXPORT const casadi_int* jac_jac_zcc_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s3;
    case 3: return casadi_s6;
    case 4: return casadi_s7;
    default: return 0;
  }
}

extern "C" CASADI_SYMBOL_EXPORT const casadi_int* jac_jac_zcc_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s8;
    case 1: return casadi_s9;
    case 2: return casadi_s10;
    case 3: return casadi_s11;
    case 4: return casadi_s12;
    case 5: return casadi_s13;
    default: return 0;
  }
}

extern "C" CASADI_SYMBOL_EXPORT int jac_jac_zcc_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 6;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

extern "C" CASADI_SYMBOL_EXPORT int jac_jac_zcc_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 6*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


